#!/bin/bash

source $CONFIG_DIR/colors.sh

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
FONT="Dank Mono Nerd"

############## BAR ##############
sketchybar --bar height=40 \
    y_offset=0 \
    position=top \
    padding_left=4 \
    padding_right=4 \
    margin=0 \
    corner_radius=0 \
    color=$BACKGROUND \
    shadow=on

############## GLOBAL DEFAULTS ##############
sketchybar --default updates=when_shown \
    icon.font="Dank Mono Nerd:Bold:16.0" \
    icon.color=0xffECEFF4 \
    icon.highlight_color=0xffE48FA8 \
    label.font="Dank Mono Nerd:Bold:16.0" \
    label.color=0xffECEFF4 \
    background.corner_radius=5 \
    background.height=30

############## LEFT ITEMS ##############
sketchybar --add item logo left \
    --set logo icon= \
    icon.color=$MANTLE \
    icon.padding_left=10 \
    icon.padding_right=9 \
    background.color=$PINK \
    background.padding_right=8 \
    background.padding_left=4 \
    background.corner_radius=999 \
    click_script="sketchybar --update"

source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

############## ITEM DEFAULTS ###############
sketchybar --default label.padding_left=6 \
    label.padding_right=6 \
    icon.padding_left=6 \
    icon.padding_right=6 \
    icon.font="Dank Mono Nerd:Bold:20.0" \
    background.height=30 \
    background.padding_right=4 \
    background.padding_left=4 \
    background.corner_radius=5

############## RIGHT ITEMS ##############

source $ITEM_DIR/time.sh
source $ITEM_DIR/date.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/net.sh
source $ITEM_DIR/cpu.sh
source $ITEM_DIR/temp.sh
source $ITEM_DIR/pressure.sh
source $ITEM_DIR/volume.sh

sketchybar --subscribe net wifi_change wired_change
sketchybar --subscribe volume volume_change

############## FINALIZING THE SETUP ##############
sketchybar --update

echo "sketchybar configuration loaded..."
